version: '3.1'
services:
  redis:
    image: redis
    ports:
      - 6379:6379
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - redis:/data
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: accointing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    extra_hosts:
    - "host.docker.internal:host-gateway"
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  redis:
    driver: local
  db-data:
    driver: local